// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataAccess.Models
{
    public partial class FoodSide
    {
        [Key]
        [Column("FoodID")]
        public int FoodId { get; set; }
        [Key]
        [Column("SideID")]
        public int SideId { get; set; }

        [ForeignKey(nameof(FoodId))]
        [InverseProperty("FoodSideFoods")]
        public virtual Food Food { get; set; }
        [ForeignKey(nameof(SideId))]
        [InverseProperty("FoodSideSides")]
        public virtual Food Side { get; set; }
    }
}