// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataAccess.Models
{
    public partial class Food
    {
        public Food()
        {
            FoodCategories = new HashSet<FoodCategory>();
            FoodSides = new HashSet<FoodSide>();
            MealFoods = new HashSet<Meal>();
            MealSoups = new HashSet<Meal>();
        }

        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column("TypeID")]
        public int TypeId { get; set; }
        [Required]
        [StringLength(200)]
        public string Name { get; set; }
        [Required]
        public bool GlutenFree { get; set; }

        [InverseProperty(nameof(FoodCategory.Food))]
        public virtual ICollection<FoodCategory> FoodCategories { get; set; }
        [InverseProperty(nameof(FoodSide.Food))]
        public virtual ICollection<FoodSide> FoodSides { get; set; }
        [InverseProperty(nameof(Meal.Food))]
        public virtual ICollection<Meal> MealFoods { get; set; }
        [InverseProperty(nameof(Meal.Soup))]
        public virtual ICollection<Meal> MealSoups { get; set; }
    }
}