// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataAccess.Models
{
    public partial class Food
    {
        public Food()
        {
            Meals = new HashSet<Meal>();
        }

        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column("CategoryID")]
        public int CategoryId { get; set; }
        [Column("TypeID")]
        public int TypeId { get; set; }
        [Required]
        [StringLength(200)]
        public string Name { get; set; }

        [ForeignKey(nameof(CategoryId))]
        [InverseProperty(nameof(FoodCategory.Foods))]
        public virtual FoodCategory Category { get; set; }
        [ForeignKey(nameof(TypeId))]
        [InverseProperty(nameof(FoodType.Foods))]
        public virtual FoodType Type { get; set; }
        [InverseProperty(nameof(Meal.Food))]
        public virtual ICollection<Meal> Meals { get; set; }
    }
}