// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataAccess.Models
{
    public partial class MealSide
    {
        [Key]
        [Column("MealID")]
        public int MealId { get; set; }
        [Key]
        [Column("SideDishesID")]
        public int SideDishesId { get; set; }

        [ForeignKey(nameof(MealId))]
        [InverseProperty("MealSides")]
        public virtual Meal Meal { get; set; }
        [ForeignKey(nameof(SideDishesId))]
        [InverseProperty(nameof(SideDish.MealSides))]
        public virtual SideDish SideDishes { get; set; }
    }
}