// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataAccess.Models
{
    public partial class Meal
    {
        public Meal()
        {
            InverseOriginalMeal = new HashSet<Meal>();
            MealCategories = new HashSet<MealCategory>();
        }

        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column("FoodID")]
        public int? FoodId { get; set; }
        [Column("TypeID")]
        public short TypeId { get; set; }
        [Column("TimeID")]
        public short TimeId { get; set; }
		[Column("SideID")]
        public int? SideId { get; set; }
        [Column("SoupID")]
        public int? SoupId { get; set; }
        [Column("OriginalMealID")]
        public int? OriginalMealId { get; set; }
        [Column(TypeName = "date")]
        public DateTime Date { get; set; }
        [StringLength(500)]
        public string Note { get; set; }

        [ForeignKey(nameof(FoodId))]
        [InverseProperty("MealFoods")]
        public virtual Food Food { get; set; }
        [ForeignKey(nameof(OriginalMealId))]
        [InverseProperty(nameof(Meal.InverseOriginalMeal))]
        public virtual Meal OriginalMeal { get; set; }
        [ForeignKey(nameof(SideId))]
        [InverseProperty(nameof(SideDish.Meals))]
        public virtual SideDish Side { get; set; }
        [ForeignKey(nameof(SoupId))]
        [InverseProperty("MealSoups")]
        public virtual Food Soup { get; set; }
        [InverseProperty(nameof(Meal.OriginalMeal))]
        public virtual ICollection<Meal> InverseOriginalMeal { get; set; }
        [InverseProperty(nameof(MealCategory.Meal))]
        public virtual ICollection<MealCategory> MealCategories { get; set; }
    }
}