// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataAccess.Models
{
    public partial class Relationship
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column("SourceID")]
        public int SourceId { get; set; }
        [Column("TargetID")]
        public int TargetId { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }

        [ForeignKey(nameof(SourceId))]
        [InverseProperty(nameof(User.RelationshipSources))]
        public virtual User Source { get; set; }
        [ForeignKey(nameof(TargetId))]
        [InverseProperty(nameof(User.RelationshipTargets))]
        public virtual User Target { get; set; }
    }
}