// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataAccess.Models
{
    public partial class SideDish
    {
        public SideDish()
        {
            FoodSides = new HashSet<FoodSide>();
            Meals = new HashSet<Meal>();
        }

        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }
        [Required]
        [StringLength(500)]
        public string Description { get; set; }
        [Required]
        public bool GlutenFree { get; set; }

        [InverseProperty(nameof(FoodSide.Side))]
        public virtual ICollection<FoodSide> FoodSides { get; set; }
        [InverseProperty(nameof(Meal.Side))]
        public virtual ICollection<Meal> Meals { get; set; }
    }
}