// <auto-generated />
using System;
using DataAccess.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccess.Migrations
{
    [DbContext(typeof(MainContext))]
    [Migration("20200415134612_SeedOther")]
    partial class SeedOther
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DataAccess.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<bool?>("IsHealthy")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasName("UK_Categories_Name");

                    b.ToTable("Categories");

                    b.HasComment("Smažené, dušení, s masem, bez masa");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Všechna sladká jídla",
                            IsHealthy = false,
                            Name = "Sladké"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Jídla, která neobsahují maso",
                            IsHealthy = true,
                            Name = "Bezmasé"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Jídla s libovolným obsahem jakéhokoliv masa",
                            Name = "S masem"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Jídla, která byla upravena procesem smažením",
                            IsHealthy = false,
                            Name = "Smažené"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Jídla, která byla upravena procesem upečením",
                            Name = "Pečené"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Jídla, která byla upravena procesem vařením",
                            Name = "Vařené"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Jídla, která byla upravena procesem grilováním",
                            IsHealthy = false,
                            Name = "Grilované"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Jídla, která byla upravena procesem dušením",
                            IsHealthy = true,
                            Name = "Dušené"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Jídla, která jsou servírována s omáčkou",
                            Name = "S omáčkou"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Jídla, která jsou servírována se sosem",
                            Name = "Se sosem"
                        });
                });

            modelBuilder.Entity("DataAccess.Models.Food", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("GlutenFree")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<int>("TypeId")
                        .HasColumnName("TypeID")
                        .HasColumnType("int")
                        .HasComment("Hlavní jídlo, polévka...");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasName("UK_Foods_Name");

                    b.ToTable("Foods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GlutenFree = true,
                            Name = "Brambory",
                            TypeId = 4
                        },
                        new
                        {
                            Id = 2,
                            GlutenFree = true,
                            Name = "Bramborová kaše",
                            TypeId = 4
                        },
                        new
                        {
                            Id = 3,
                            GlutenFree = true,
                            Name = "Knedlíky",
                            TypeId = 4
                        },
                        new
                        {
                            Id = 4,
                            GlutenFree = true,
                            Name = "Rýže",
                            TypeId = 4
                        },
                        new
                        {
                            Id = 5,
                            GlutenFree = true,
                            Name = "Těstoviny",
                            TypeId = 4
                        },
                        new
                        {
                            Id = 6,
                            GlutenFree = true,
                            Name = "Hranolky",
                            TypeId = 4
                        },
                        new
                        {
                            Id = 7,
                            GlutenFree = true,
                            Name = "Pečivo",
                            TypeId = 4
                        },
                        new
                        {
                            Id = 8,
                            GlutenFree = true,
                            Name = "Zelenina",
                            TypeId = 4
                        },
                        new
                        {
                            Id = 9,
                            GlutenFree = true,
                            Name = "Kotlety na cibulce",
                            TypeId = 1
                        },
                        new
                        {
                            Id = 10,
                            GlutenFree = true,
                            Name = "Ražniči",
                            TypeId = 1
                        },
                        new
                        {
                            Id = 11,
                            GlutenFree = true,
                            Name = "Naložené kuřecí plátky",
                            TypeId = 1
                        },
                        new
                        {
                            Id = 12,
                            GlutenFree = true,
                            Name = "Naložené vepřové plátky",
                            TypeId = 1
                        },
                        new
                        {
                            Id = 13,
                            GlutenFree = true,
                            Name = "Knedlo, vepřo, zelo",
                            TypeId = 1
                        },
                        new
                        {
                            Id = 14,
                            GlutenFree = true,
                            Name = "Knedlo, vepřo, špenát",
                            TypeId = 1
                        },
                        new
                        {
                            Id = 15,
                            GlutenFree = true,
                            Name = "Špenát s vajíčkem",
                            TypeId = 1
                        },
                        new
                        {
                            Id = 16,
                            GlutenFree = true,
                            Name = "Řízky",
                            TypeId = 1
                        },
                        new
                        {
                            Id = 17,
                            GlutenFree = true,
                            Name = "Filé",
                            TypeId = 1
                        },
                        new
                        {
                            Id = 18,
                            GlutenFree = true,
                            Name = "Sekaná",
                            TypeId = 1
                        },
                        new
                        {
                            Id = 19,
                            GlutenFree = true,
                            Name = "Rizoto kuřecí",
                            TypeId = 1
                        },
                        new
                        {
                            Id = 20,
                            GlutenFree = true,
                            Name = "Rizoto vepřové",
                            TypeId = 1
                        },
                        new
                        {
                            Id = 21,
                            GlutenFree = true,
                            Name = "Kuře na papirce",
                            TypeId = 1
                        },
                        new
                        {
                            Id = 22,
                            GlutenFree = true,
                            Name = "Rajská",
                            TypeId = 1
                        },
                        new
                        {
                            Id = 23,
                            GlutenFree = true,
                            Name = "Guláš",
                            TypeId = 1
                        },
                        new
                        {
                            Id = 24,
                            GlutenFree = true,
                            Name = "Buřt guláš",
                            TypeId = 1
                        },
                        new
                        {
                            Id = 25,
                            GlutenFree = true,
                            Name = "Ptáčky",
                            TypeId = 1
                        },
                        new
                        {
                            Id = 26,
                            GlutenFree = true,
                            Name = "Houbová omáčka",
                            TypeId = 1
                        },
                        new
                        {
                            Id = 27,
                            GlutenFree = true,
                            Name = "Koprovka",
                            TypeId = 1
                        },
                        new
                        {
                            Id = 28,
                            GlutenFree = true,
                            Name = "Šunkafleky",
                            TypeId = 1
                        },
                        new
                        {
                            Id = 29,
                            GlutenFree = true,
                            Name = "Zapečné brambory",
                            TypeId = 1
                        },
                        new
                        {
                            Id = 30,
                            GlutenFree = true,
                            Name = "Maso ve smetanové omáčce",
                            TypeId = 1
                        },
                        new
                        {
                            Id = 31,
                            GlutenFree = true,
                            Name = "Maso zapečené s kečupem",
                            TypeId = 1
                        },
                        new
                        {
                            Id = 32,
                            GlutenFree = true,
                            Name = "Kuře s nádivkou",
                            TypeId = 1
                        },
                        new
                        {
                            Id = 33,
                            GlutenFree = true,
                            Name = "Klobása",
                            TypeId = 1
                        },
                        new
                        {
                            Id = 34,
                            GlutenFree = true,
                            Name = "Kuřecí kapsa",
                            TypeId = 1
                        },
                        new
                        {
                            Id = 35,
                            GlutenFree = true,
                            Name = "Smažený sýr",
                            TypeId = 1
                        },
                        new
                        {
                            Id = 36,
                            GlutenFree = true,
                            Name = "Žampiony",
                            TypeId = 1
                        },
                        new
                        {
                            Id = 37,
                            GlutenFree = true,
                            Name = "Květák",
                            TypeId = 1
                        },
                        new
                        {
                            Id = 38,
                            GlutenFree = true,
                            Name = "Holandký řízek",
                            TypeId = 1
                        },
                        new
                        {
                            Id = 39,
                            GlutenFree = true,
                            Name = "Halušky",
                            TypeId = 1
                        },
                        new
                        {
                            Id = 40,
                            GlutenFree = true,
                            Name = "Špagety",
                            TypeId = 1
                        },
                        new
                        {
                            Id = 41,
                            GlutenFree = true,
                            Name = "Těstoviny stuňákem",
                            TypeId = 1
                        },
                        new
                        {
                            Id = 42,
                            GlutenFree = true,
                            Name = "Bramboráky",
                            TypeId = 1
                        },
                        new
                        {
                            Id = 43,
                            GlutenFree = true,
                            Name = "Roláda kuřecí",
                            TypeId = 1
                        },
                        new
                        {
                            Id = 44,
                            GlutenFree = true,
                            Name = "Roláda vepřová",
                            TypeId = 1
                        },
                        new
                        {
                            Id = 45,
                            GlutenFree = true,
                            Name = "Dušení mrkev + maso",
                            TypeId = 1
                        },
                        new
                        {
                            Id = 46,
                            GlutenFree = true,
                            Name = "Čína",
                            TypeId = 1
                        },
                        new
                        {
                            Id = 47,
                            GlutenFree = true,
                            Name = "Karbanátky",
                            TypeId = 1
                        },
                        new
                        {
                            Id = 48,
                            GlutenFree = true,
                            Name = "Čevabčiči",
                            TypeId = 1
                        },
                        new
                        {
                            Id = 49,
                            GlutenFree = true,
                            Name = "Kuřecí plátek v alobalu",
                            TypeId = 1
                        },
                        new
                        {
                            Id = 50,
                            GlutenFree = true,
                            Name = "Johančino tajemství",
                            TypeId = 1
                        },
                        new
                        {
                            Id = 51,
                            GlutenFree = true,
                            Name = "Čočka na kyselo",
                            TypeId = 1
                        },
                        new
                        {
                            Id = 52,
                            GlutenFree = true,
                            Name = "Míchaná zelenina",
                            TypeId = 1
                        },
                        new
                        {
                            Id = 53,
                            GlutenFree = true,
                            Name = "Pečené maso",
                            TypeId = 1
                        },
                        new
                        {
                            Id = 54,
                            GlutenFree = true,
                            Name = "Buřtgulášová polévka",
                            TypeId = 2
                        },
                        new
                        {
                            Id = 55,
                            GlutenFree = true,
                            Name = "Česnečka",
                            TypeId = 2
                        },
                        new
                        {
                            Id = 56,
                            GlutenFree = true,
                            Name = "Bramboračka",
                            TypeId = 2
                        },
                        new
                        {
                            Id = 57,
                            GlutenFree = true,
                            Name = "Pórková polévka",
                            TypeId = 2
                        },
                        new
                        {
                            Id = 58,
                            GlutenFree = true,
                            Name = "Houbová polévka",
                            TypeId = 2
                        },
                        new
                        {
                            Id = 59,
                            GlutenFree = true,
                            Name = "Polévka z kuřecího vývaru",
                            TypeId = 2
                        },
                        new
                        {
                            Id = 60,
                            GlutenFree = true,
                            Name = "Špenátová polévka",
                            TypeId = 2
                        });
                });

            modelBuilder.Entity("DataAccess.Models.FoodCategory", b =>
                {
                    b.Property<int>("FoodId")
                        .HasColumnName("FoodID")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnName("CategoryID")
                        .HasColumnType("int");

                    b.HasKey("FoodId", "CategoryId")
                        .HasName("PK_FoodCategories_1");

                    b.HasIndex("CategoryId");

                    b.ToTable("FoodCategories");

                    b.HasComment("");

                    b.HasData(
                        new
                        {
                            FoodId = 9,
                            CategoryId = 3
                        },
                        new
                        {
                            FoodId = 9,
                            CategoryId = 5
                        },
                        new
                        {
                            FoodId = 10,
                            CategoryId = 3
                        },
                        new
                        {
                            FoodId = 10,
                            CategoryId = 5
                        },
                        new
                        {
                            FoodId = 11,
                            CategoryId = 3
                        },
                        new
                        {
                            FoodId = 11,
                            CategoryId = 5
                        },
                        new
                        {
                            FoodId = 12,
                            CategoryId = 3
                        },
                        new
                        {
                            FoodId = 12,
                            CategoryId = 5
                        },
                        new
                        {
                            FoodId = 13,
                            CategoryId = 3
                        },
                        new
                        {
                            FoodId = 13,
                            CategoryId = 5
                        },
                        new
                        {
                            FoodId = 14,
                            CategoryId = 3
                        },
                        new
                        {
                            FoodId = 14,
                            CategoryId = 5
                        },
                        new
                        {
                            FoodId = 15,
                            CategoryId = 2
                        },
                        new
                        {
                            FoodId = 15,
                            CategoryId = 5
                        },
                        new
                        {
                            FoodId = 16,
                            CategoryId = 3
                        },
                        new
                        {
                            FoodId = 16,
                            CategoryId = 4
                        },
                        new
                        {
                            FoodId = 17,
                            CategoryId = 3
                        },
                        new
                        {
                            FoodId = 17,
                            CategoryId = 5
                        },
                        new
                        {
                            FoodId = 18,
                            CategoryId = 3
                        },
                        new
                        {
                            FoodId = 18,
                            CategoryId = 5
                        },
                        new
                        {
                            FoodId = 19,
                            CategoryId = 3
                        },
                        new
                        {
                            FoodId = 19,
                            CategoryId = 5
                        },
                        new
                        {
                            FoodId = 20,
                            CategoryId = 3
                        },
                        new
                        {
                            FoodId = 20,
                            CategoryId = 5
                        },
                        new
                        {
                            FoodId = 21,
                            CategoryId = 3
                        },
                        new
                        {
                            FoodId = 21,
                            CategoryId = 5
                        },
                        new
                        {
                            FoodId = 21,
                            CategoryId = 9
                        },
                        new
                        {
                            FoodId = 22,
                            CategoryId = 3
                        },
                        new
                        {
                            FoodId = 22,
                            CategoryId = 5
                        },
                        new
                        {
                            FoodId = 22,
                            CategoryId = 9
                        },
                        new
                        {
                            FoodId = 23,
                            CategoryId = 3
                        },
                        new
                        {
                            FoodId = 23,
                            CategoryId = 6
                        },
                        new
                        {
                            FoodId = 23,
                            CategoryId = 9
                        },
                        new
                        {
                            FoodId = 24,
                            CategoryId = 3
                        },
                        new
                        {
                            FoodId = 24,
                            CategoryId = 6
                        },
                        new
                        {
                            FoodId = 24,
                            CategoryId = 9
                        },
                        new
                        {
                            FoodId = 25,
                            CategoryId = 3
                        },
                        new
                        {
                            FoodId = 25,
                            CategoryId = 5
                        },
                        new
                        {
                            FoodId = 26,
                            CategoryId = 3
                        },
                        new
                        {
                            FoodId = 26,
                            CategoryId = 6
                        },
                        new
                        {
                            FoodId = 26,
                            CategoryId = 9
                        },
                        new
                        {
                            FoodId = 27,
                            CategoryId = 2
                        },
                        new
                        {
                            FoodId = 27,
                            CategoryId = 6
                        },
                        new
                        {
                            FoodId = 28,
                            CategoryId = 3
                        },
                        new
                        {
                            FoodId = 28,
                            CategoryId = 5
                        },
                        new
                        {
                            FoodId = 29,
                            CategoryId = 3
                        },
                        new
                        {
                            FoodId = 29,
                            CategoryId = 5
                        },
                        new
                        {
                            FoodId = 30,
                            CategoryId = 3
                        },
                        new
                        {
                            FoodId = 30,
                            CategoryId = 5
                        },
                        new
                        {
                            FoodId = 30,
                            CategoryId = 9
                        },
                        new
                        {
                            FoodId = 31,
                            CategoryId = 3
                        },
                        new
                        {
                            FoodId = 31,
                            CategoryId = 5
                        },
                        new
                        {
                            FoodId = 32,
                            CategoryId = 3
                        },
                        new
                        {
                            FoodId = 32,
                            CategoryId = 5
                        },
                        new
                        {
                            FoodId = 33,
                            CategoryId = 3
                        },
                        new
                        {
                            FoodId = 33,
                            CategoryId = 5
                        },
                        new
                        {
                            FoodId = 33,
                            CategoryId = 7
                        },
                        new
                        {
                            FoodId = 34,
                            CategoryId = 3
                        },
                        new
                        {
                            FoodId = 34,
                            CategoryId = 5
                        },
                        new
                        {
                            FoodId = 35,
                            CategoryId = 3
                        },
                        new
                        {
                            FoodId = 35,
                            CategoryId = 4
                        },
                        new
                        {
                            FoodId = 36,
                            CategoryId = 2
                        },
                        new
                        {
                            FoodId = 36,
                            CategoryId = 4
                        },
                        new
                        {
                            FoodId = 36,
                            CategoryId = 5
                        },
                        new
                        {
                            FoodId = 37,
                            CategoryId = 2
                        },
                        new
                        {
                            FoodId = 37,
                            CategoryId = 4
                        },
                        new
                        {
                            FoodId = 38,
                            CategoryId = 3
                        },
                        new
                        {
                            FoodId = 38,
                            CategoryId = 5
                        },
                        new
                        {
                            FoodId = 39,
                            CategoryId = 3
                        },
                        new
                        {
                            FoodId = 39,
                            CategoryId = 5
                        },
                        new
                        {
                            FoodId = 40,
                            CategoryId = 3
                        },
                        new
                        {
                            FoodId = 40,
                            CategoryId = 6
                        },
                        new
                        {
                            FoodId = 41,
                            CategoryId = 3
                        },
                        new
                        {
                            FoodId = 41,
                            CategoryId = 6
                        },
                        new
                        {
                            FoodId = 42,
                            CategoryId = 2
                        },
                        new
                        {
                            FoodId = 42,
                            CategoryId = 4
                        },
                        new
                        {
                            FoodId = 43,
                            CategoryId = 3
                        },
                        new
                        {
                            FoodId = 43,
                            CategoryId = 5
                        },
                        new
                        {
                            FoodId = 44,
                            CategoryId = 3
                        },
                        new
                        {
                            FoodId = 44,
                            CategoryId = 5
                        },
                        new
                        {
                            FoodId = 45,
                            CategoryId = 3
                        },
                        new
                        {
                            FoodId = 45,
                            CategoryId = 5
                        },
                        new
                        {
                            FoodId = 45,
                            CategoryId = 8
                        },
                        new
                        {
                            FoodId = 46,
                            CategoryId = 3
                        },
                        new
                        {
                            FoodId = 46,
                            CategoryId = 5
                        },
                        new
                        {
                            FoodId = 47,
                            CategoryId = 3
                        },
                        new
                        {
                            FoodId = 47,
                            CategoryId = 5
                        },
                        new
                        {
                            FoodId = 48,
                            CategoryId = 3
                        },
                        new
                        {
                            FoodId = 48,
                            CategoryId = 5
                        },
                        new
                        {
                            FoodId = 49,
                            CategoryId = 3
                        },
                        new
                        {
                            FoodId = 49,
                            CategoryId = 5
                        },
                        new
                        {
                            FoodId = 50,
                            CategoryId = 3
                        },
                        new
                        {
                            FoodId = 50,
                            CategoryId = 5
                        },
                        new
                        {
                            FoodId = 51,
                            CategoryId = 3
                        },
                        new
                        {
                            FoodId = 51,
                            CategoryId = 6
                        },
                        new
                        {
                            FoodId = 52,
                            CategoryId = 2
                        },
                        new
                        {
                            FoodId = 52,
                            CategoryId = 5
                        },
                        new
                        {
                            FoodId = 53,
                            CategoryId = 3
                        },
                        new
                        {
                            FoodId = 53,
                            CategoryId = 5
                        },
                        new
                        {
                            FoodId = 54,
                            CategoryId = 3
                        },
                        new
                        {
                            FoodId = 55,
                            CategoryId = 2
                        },
                        new
                        {
                            FoodId = 56,
                            CategoryId = 2
                        },
                        new
                        {
                            FoodId = 57,
                            CategoryId = 2
                        },
                        new
                        {
                            FoodId = 58,
                            CategoryId = 2
                        },
                        new
                        {
                            FoodId = 59,
                            CategoryId = 3
                        },
                        new
                        {
                            FoodId = 60,
                            CategoryId = 2
                        });
                });

            modelBuilder.Entity("DataAccess.Models.FoodSide", b =>
                {
                    b.Property<int>("FoodId")
                        .HasColumnName("FoodID")
                        .HasColumnType("int");

                    b.Property<int>("SideId")
                        .HasColumnName("SideID")
                        .HasColumnType("int");

                    b.HasKey("FoodId", "SideId");

                    b.HasIndex("SideId");

                    b.ToTable("FoodSides");

                    b.HasComment("Defaultní přílohy k jídlům");

                    b.HasData(
                        new
                        {
                            FoodId = 9,
                            SideId = 1
                        },
                        new
                        {
                            FoodId = 9,
                            SideId = 2
                        },
                        new
                        {
                            FoodId = 10,
                            SideId = 1
                        },
                        new
                        {
                            FoodId = 11,
                            SideId = 1
                        },
                        new
                        {
                            FoodId = 11,
                            SideId = 6
                        },
                        new
                        {
                            FoodId = 12,
                            SideId = 1
                        },
                        new
                        {
                            FoodId = 12,
                            SideId = 6
                        },
                        new
                        {
                            FoodId = 13,
                            SideId = 3
                        },
                        new
                        {
                            FoodId = 14,
                            SideId = 3
                        },
                        new
                        {
                            FoodId = 15,
                            SideId = 1
                        },
                        new
                        {
                            FoodId = 16,
                            SideId = 1
                        },
                        new
                        {
                            FoodId = 16,
                            SideId = 2
                        },
                        new
                        {
                            FoodId = 16,
                            SideId = 6
                        },
                        new
                        {
                            FoodId = 17,
                            SideId = 1
                        },
                        new
                        {
                            FoodId = 17,
                            SideId = 2
                        },
                        new
                        {
                            FoodId = 18,
                            SideId = 1
                        },
                        new
                        {
                            FoodId = 18,
                            SideId = 2
                        },
                        new
                        {
                            FoodId = 21,
                            SideId = 1
                        },
                        new
                        {
                            FoodId = 21,
                            SideId = 3
                        },
                        new
                        {
                            FoodId = 22,
                            SideId = 1
                        },
                        new
                        {
                            FoodId = 22,
                            SideId = 3
                        },
                        new
                        {
                            FoodId = 23,
                            SideId = 1
                        },
                        new
                        {
                            FoodId = 23,
                            SideId = 5
                        },
                        new
                        {
                            FoodId = 24,
                            SideId = 1
                        },
                        new
                        {
                            FoodId = 25,
                            SideId = 1
                        },
                        new
                        {
                            FoodId = 25,
                            SideId = 2
                        },
                        new
                        {
                            FoodId = 25,
                            SideId = 4
                        },
                        new
                        {
                            FoodId = 26,
                            SideId = 1
                        },
                        new
                        {
                            FoodId = 27,
                            SideId = 1
                        },
                        new
                        {
                            FoodId = 27,
                            SideId = 3
                        },
                        new
                        {
                            FoodId = 30,
                            SideId = 1
                        },
                        new
                        {
                            FoodId = 30,
                            SideId = 6
                        },
                        new
                        {
                            FoodId = 31,
                            SideId = 1
                        },
                        new
                        {
                            FoodId = 31,
                            SideId = 6
                        },
                        new
                        {
                            FoodId = 32,
                            SideId = 1
                        },
                        new
                        {
                            FoodId = 33,
                            SideId = 1
                        },
                        new
                        {
                            FoodId = 33,
                            SideId = 2
                        },
                        new
                        {
                            FoodId = 33,
                            SideId = 7
                        },
                        new
                        {
                            FoodId = 33,
                            SideId = 8
                        },
                        new
                        {
                            FoodId = 34,
                            SideId = 1
                        },
                        new
                        {
                            FoodId = 34,
                            SideId = 2
                        },
                        new
                        {
                            FoodId = 34,
                            SideId = 6
                        },
                        new
                        {
                            FoodId = 35,
                            SideId = 1
                        },
                        new
                        {
                            FoodId = 35,
                            SideId = 6
                        },
                        new
                        {
                            FoodId = 36,
                            SideId = 1
                        },
                        new
                        {
                            FoodId = 36,
                            SideId = 6
                        },
                        new
                        {
                            FoodId = 37,
                            SideId = 1
                        },
                        new
                        {
                            FoodId = 37,
                            SideId = 6
                        },
                        new
                        {
                            FoodId = 38,
                            SideId = 1
                        },
                        new
                        {
                            FoodId = 38,
                            SideId = 2
                        },
                        new
                        {
                            FoodId = 43,
                            SideId = 1
                        },
                        new
                        {
                            FoodId = 43,
                            SideId = 2
                        },
                        new
                        {
                            FoodId = 43,
                            SideId = 4
                        },
                        new
                        {
                            FoodId = 43,
                            SideId = 6
                        },
                        new
                        {
                            FoodId = 44,
                            SideId = 1
                        },
                        new
                        {
                            FoodId = 44,
                            SideId = 2
                        },
                        new
                        {
                            FoodId = 44,
                            SideId = 4
                        },
                        new
                        {
                            FoodId = 44,
                            SideId = 6
                        },
                        new
                        {
                            FoodId = 45,
                            SideId = 1
                        },
                        new
                        {
                            FoodId = 47,
                            SideId = 1
                        },
                        new
                        {
                            FoodId = 47,
                            SideId = 2
                        },
                        new
                        {
                            FoodId = 48,
                            SideId = 1
                        },
                        new
                        {
                            FoodId = 48,
                            SideId = 2
                        },
                        new
                        {
                            FoodId = 49,
                            SideId = 1
                        },
                        new
                        {
                            FoodId = 49,
                            SideId = 2
                        },
                        new
                        {
                            FoodId = 49,
                            SideId = 4
                        },
                        new
                        {
                            FoodId = 49,
                            SideId = 6
                        },
                        new
                        {
                            FoodId = 50,
                            SideId = 1
                        },
                        new
                        {
                            FoodId = 50,
                            SideId = 2
                        },
                        new
                        {
                            FoodId = 50,
                            SideId = 6
                        },
                        new
                        {
                            FoodId = 51,
                            SideId = 7
                        },
                        new
                        {
                            FoodId = 52,
                            SideId = 1
                        },
                        new
                        {
                            FoodId = 52,
                            SideId = 7
                        },
                        new
                        {
                            FoodId = 53,
                            SideId = 1
                        },
                        new
                        {
                            FoodId = 53,
                            SideId = 7
                        });
                });

            modelBuilder.Entity("DataAccess.Models.Meal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<int?>("FoodId")
                        .HasColumnName("FoodID")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<int?>("OriginalMealId")
                        .HasColumnName("OriginalMealID")
                        .HasColumnType("int");

                    b.Property<int?>("SideId")
                        .HasColumnName("SideID")
                        .HasColumnType("int");

                    b.Property<int?>("SoupId")
                        .HasColumnName("SoupID")
                        .HasColumnType("int");

                    b.Property<short>("TimeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("TimeID")
                        .HasColumnType("smallint")
                        .HasDefaultValueSql("((2))")
                        .HasComment("Snídaně, oběd, večeře");

                    b.Property<short>("TypeId")
                        .HasColumnName("TypeID")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("FoodId");

                    b.HasIndex("OriginalMealId");

                    b.HasIndex("SideId");

                    b.HasIndex("SoupId");

                    b.ToTable("Meals");

                    b.HasComment("Jídla v jednotlivé dny");
                });

            modelBuilder.Entity("DataAccess.Models.MealCategory", b =>
                {
                    b.Property<int>("MealId")
                        .HasColumnName("MealID")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnName("CategoryID")
                        .HasColumnType("int");

                    b.HasKey("MealId", "CategoryId")
                        .HasName("PK_MealCategories_1");

                    b.HasIndex("CategoryId");

                    b.ToTable("MealCategories");

                    b.HasComment("");
                });

            modelBuilder.Entity("DataAccess.Models.Token", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("Expiration")
                        .HasColumnType("datetime");

                    b.Property<string>("TokenString")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<int>("UserId")
                        .HasColumnName("UserID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Tokens");
                });

            modelBuilder.Entity("DataAccess.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("GoogleId")
                        .IsRequired()
                        .HasColumnName("GoogleID")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasName("UK_Users_Email");

                    b.HasIndex("GoogleId")
                        .IsUnique()
                        .HasName("UK_Users_Google");

                    b.ToTable("Users");

                    b.HasComment("");
                });

            modelBuilder.Entity("DataAccess.Models.FoodCategory", b =>
                {
                    b.HasOne("DataAccess.Models.Category", "Category")
                        .WithMany("FoodCategories")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK_FoodCategories_Categories")
                        .IsRequired();

                    b.HasOne("DataAccess.Models.Food", "Food")
                        .WithMany("FoodCategories")
                        .HasForeignKey("FoodId")
                        .HasConstraintName("FK_FoodCategories_Foods")
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccess.Models.FoodSide", b =>
                {
                    b.HasOne("DataAccess.Models.Food", "Food")
                        .WithMany("FoodSideFoods")
                        .HasForeignKey("FoodId")
                        .HasConstraintName("FK_FoodSides_Foods")
                        .IsRequired();

                    b.HasOne("DataAccess.Models.Food", "Side")
                        .WithMany("FoodSideSides")
                        .HasForeignKey("SideId")
                        .HasConstraintName("FK_FoodSides_Side")
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccess.Models.Meal", b =>
                {
                    b.HasOne("DataAccess.Models.Food", "Food")
                        .WithMany("MealFoods")
                        .HasForeignKey("FoodId")
                        .HasConstraintName("FK_Meals_Foods");

                    b.HasOne("DataAccess.Models.Meal", "OriginalMeal")
                        .WithMany("InverseOriginalMeal")
                        .HasForeignKey("OriginalMealId")
                        .HasConstraintName("FK_Meals_OriginalMeals");

                    b.HasOne("DataAccess.Models.Food", "Side")
                        .WithMany("MealSides")
                        .HasForeignKey("SideId")
                        .HasConstraintName("FK_Meals_SideDish");

                    b.HasOne("DataAccess.Models.Food", "Soup")
                        .WithMany("MealSoups")
                        .HasForeignKey("SoupId")
                        .HasConstraintName("FK_Meals_Soup");
                });

            modelBuilder.Entity("DataAccess.Models.MealCategory", b =>
                {
                    b.HasOne("DataAccess.Models.Category", "Category")
                        .WithMany("MealCategories")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK_MealCategories_Categories")
                        .IsRequired();

                    b.HasOne("DataAccess.Models.Meal", "Meal")
                        .WithMany("MealCategories")
                        .HasForeignKey("MealId")
                        .HasConstraintName("FK_MealCategories_Meals")
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccess.Models.Token", b =>
                {
                    b.HasOne("DataAccess.Models.User", "User")
                        .WithMany("Tokens")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Tokens_Users")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
