// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DataAccess.Models;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace DataAccess.Contexts
{
    public partial class MainContext : DbContext
    {
        public MainContext()
        {
			this.Database.EnsureCreated();
        }

        public MainContext(DbContextOptions<MainContext> options)
            : base(options)
        {
			this.Database.EnsureCreated();
        }

        public virtual DbSet<Food> Foods { get; set; }
        public virtual DbSet<FoodCategory> FoodCategories { get; set; }
        public virtual DbSet<FoodSide> FoodSides { get; set; }
        public virtual DbSet<FoodType> FoodTypes { get; set; }
        public virtual DbSet<Meal> Meals { get; set; }
        public virtual DbSet<MealSide> MealSides { get; set; }
        public virtual DbSet<MealType> MealTypes { get; set; }
        public virtual DbSet<Relationship> Relationships { get; set; }
        public virtual DbSet<SideDish> SideDishes { get; set; }
        public virtual DbSet<Token> Tokens { get; set; }
        public virtual DbSet<User> Users { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Food>(entity =>
            {
                entity.Property(e => e.CategoryId).HasComment("Bezmasé, S masem, Sladké...");

                entity.Property(e => e.TypeId).HasComment("Hlavní jídlo, polévka...");

                entity.HasOne(d => d.Category)
                    .WithMany(p => p.Foods)
                    .HasForeignKey(d => d.CategoryId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Foods_FoodCategories");

                entity.HasOne(d => d.Type)
                    .WithMany(p => p.Foods)
                    .HasForeignKey(d => d.TypeId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Foods_FoodTypes");
            });

            modelBuilder.Entity<FoodCategory>(entity =>
            {
                entity.HasComment("Sladká, Bezmassá, s masem...");
            });

            modelBuilder.Entity<FoodSide>(entity =>
            {
                entity.HasKey(e => new { e.FoodId, e.SideId });

                entity.HasComment("Defaultní přílohy k jídlům");

                entity.HasOne(d => d.Food)
                    .WithMany(p => p.FoodSides)
                    .HasForeignKey(d => d.FoodId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_FoodSides_Foods");

                entity.HasOne(d => d.Side)
                    .WithMany(p => p.FoodSides)
                    .HasForeignKey(d => d.SideId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_FoodSides_SideDishes");
            });

            modelBuilder.Entity<FoodType>(entity =>
            {
                entity.HasComment("Polévka, hlavní jídla...");
            });

            modelBuilder.Entity<Meal>(entity =>
            {
                entity.HasOne(d => d.CookedBy)
                    .WithMany(p => p.Meals)
                    .HasForeignKey(d => d.CookedById)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Meals_Users");

                entity.HasOne(d => d.Food)
                    .WithMany(p => p.Meals)
                    .HasForeignKey(d => d.FoodId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Meals_Foods");

                entity.HasOne(d => d.Type)
                    .WithMany(p => p.Meals)
                    .HasForeignKey(d => d.TypeId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Meals_MealTypes");
            });

            modelBuilder.Entity<MealSide>(entity =>
            {
                entity.HasKey(e => new { e.MealId, e.SideDishesId });

                entity.HasOne(d => d.Meal)
                    .WithMany(p => p.MealSides)
                    .HasForeignKey(d => d.MealId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_MealSides_Meals");

                entity.HasOne(d => d.SideDishes)
                    .WithMany(p => p.MealSides)
                    .HasForeignKey(d => d.SideDishesId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_MealSides_SideDishes");
            });

            modelBuilder.Entity<MealType>(entity =>
            {
                entity.HasComment("Hlavní jídlo, krabička, ...");
            });

            modelBuilder.Entity<Relationship>(entity =>
            {
                entity.HasComment("Otec, Matka...");

                entity.Property(e => e.Id).ValueGeneratedNever();

                entity.HasOne(d => d.Source)
                    .WithMany(p => p.RelationshipSources)
                    .HasForeignKey(d => d.SourceId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Relationships_Source");

                entity.HasOne(d => d.Target)
                    .WithMany(p => p.RelationshipTargets)
                    .HasForeignKey(d => d.TargetId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Relationships_Target");
            });

            modelBuilder.Entity<SideDish>(entity =>
            {
                entity.HasComment("Přilohy");

                entity.Property(e => e.GlutenFree)
                    .HasDefaultValueSql("((1))")
                    .HasComment("Bez lepku");
            });

            modelBuilder.Entity<Token>(entity =>
            {
                entity.Property(e => e.Created).HasDefaultValueSql("(getdate())");

                entity.HasOne(d => d.User)
                    .WithMany(p => p.Tokens)
                    .HasForeignKey(d => d.UserId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Tokens_Users");
            });

            modelBuilder.Entity<User>(entity =>
            {
                entity.HasComment("");

                entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");

                entity.Property(e => e.Email).IsUnicode(false);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}